### ISSUE TITLE
Feature: Choose white/black color

### ISSUE THREAD

**Issue by Diwakar-Gupta** [Diwakar-Gupta/Chess#13]
Add option to start new game as black or white.
This will be followed by changing view angle of the board, which can be done by changing the order of rendering.

**Comment by Trevy05** [comment]
Can you assign this issue to me? I'd like to work on this.

**Comment by Diwakar-Gupta** [comment]
@Trevy05 You are welcome to open a PR to address this issue.

You can begin working on a issue by leaving a comment saying you wish to work on it and then opening the PR.
